export const details = [
  // export default [
  {
    id: '1',
    customerName: 'test',
    customerMobile: 9788898999,
    addressLine: 1,
    addressLine: 2,
    pincode: '',
    city: '',
    state: '',
    customerAge: 0,
    customerFatherName: '',
    owning: '',
    creationDate: '',
    status: 'Not TRIGGERED',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRWTBeX5wowkab5SQvCH4nno2GTCrJu3SXMA&usqp=CAU',
  },
  {
    id: '2',
    customerName: 'test',
    customerMobile: 9788898999,
    addressLine: 1,
    addressLine: 2,
    pincode: '',
    city: '',
    state: '',
    customerAge: 0,
    customerFatherName: '',
    owning: '',
    creationDate: '',
    status: 'Not TRIGGERED',
    image:
      'https://companieslogo.com/img/orig/ASIANPAINT.NS-6124f67e.png?t=1596837431',
  },
  {
    id: '3',
    customerName: 'test',
    customerMobile: 9788898999,
    addressLine: 1,
    addressLine: 2,
    pincode: '',
    city: '',
    state: '',
    customerAge: 0,
    customerFatherName: '',
    owning: '',
    creationDate: '',
    status: 'Not TRIGGERED',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRWTBeX5wowkab5SQvCH4nno2GTCrJu3SXMA&usqp=CAU',
  },
  {
    id: '4',
    customerName: 'test',
    customerMobile: 9788898999,
    addressLine: 1,
    addressLine: 2,
    pincode: '',
    city: '',
    state: '',
    customerAge: 0,
    customerFatherName: '',
    owning: '',
    creationDate: '',
    status: 'Not TRIGGERED',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRWTBeX5wowkab5SQvCH4nno2GTCrJu3SXMA&usqp=CAU',
  },
  {
    id: '5',
    customerName: 'test',
    customerMobile: 9788898999,
    addressLine: 1,
    addressLine: 2,
    pincode: '',
    city: '',
    state: '',
    customerAge: 0,
    customerFatherName: '',
    owning: '',
    creationDate: '',
    status: 'Not TRIGGERED',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRWTBeX5wowkab5SQvCH4nno2GTCrJu3SXMA&usqp=CAU',
  },
  {
    id: '6',
    customerName: 'test',
    customerMobile: 9788898999,
    addressLine: 1,
    addressLine: 2,
    pincode: '',
    city: '',
    state: '',
    customerAge: 0,
    customerFatherName: '',
    owning: '',
    creationDate: '',
    status: 'Not TRIGGERED',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRWTBeX5wowkab5SQvCH4nno2GTCrJu3SXMA&usqp=CAU',
  },
];

//
